#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ESB.Resource", IsApplication=true)]

namespace ESB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int esblogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int button1 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int button2 = 2131034139;
			
			// aapt resource value: 0x7f05000a
			public const int button_start_hr = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button_stop_hr = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int consoleText = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int demoScroller = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int demoTitle = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int deviceList = 2131034137;
			
			// aapt resource value: 0x7f050001
			public const int hr = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int plotViewModel = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int progressBar = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int progressBarTitle = 2131034135;
			
			// aapt resource value: 0x7f05000c
			public const int progress_work = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int rawhr = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int rawsp = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int separator = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int separator1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int separator2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int separator3 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int separator4 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int sp = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int temp = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int textBattery = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int textDeviceName = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textHR = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int textInfo = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int textInfo2 = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int textNow = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChartView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Heart = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LogView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int refreshing = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
